### ISSUE TITLE
Historgram value in statistics is not a list when there are not enough values

### ISSUE THREAD

**Issue by luos** [folsom-project/bear#10]
Hi,

When I call `bear:get_statistics([])` (so getting the statistics for less than a couple elements), the result is the following:

```
(folsom_test_app@127.0.0.1)12> bear:get_statistics([]).
[{min,0.0},
 {max,0.0},
 {arithmetic_mean,0.0},
 {geometric_mean,0.0},
 {harmonic_mean,0.0},
 {median,0.0},
 {variance,0.0},
 {standard_deviation,0.0},
 {skewness,0.0},
 {kurtosis,0.0},
 {percentile,[{50,0.0},
              {75,0.0},
              {90,0.0},
              {95,0.0},
              {99,0.0},
              {999,0.0}]},
 {histogram,[{0,0}]},
 {n,0}] 
```
Note the { {histogram,[{0,0}]},} part. 
However when I call `bear:get_statistics_subset([1,2,3],[histogram]).` the result is this: 

```
[{histogram,0.0}]
```

I think the value should be either an empty list or [{0,0}]. What do you think?

When I have more elements, it starts working properly: 
```
bear:get_statistics_subset([1,2,3,4,5,6,7],[histogram]).
[{histogram,[{5,5},{9,2},{13,0}]}]
```

This is causing an issue for me in `folsom_metrics:get_histogram_statistics` when there are only a few samples cause the "shape" of the result is dependent on the number of samples. 

What do you think? 

Thanks,
Lajos

**Comment by joewilliams** [comment]
@luos sorry for not getting back to you sooner but yes, this makes sense to me. I think we'd likely just want to make [`get_histogram`](https://github.com/folsom-project/bear/blob/master/src/bear.erl#L274) return `[]` when the number of values are less than `STATS_MIN`.

**Comment by joewilliams** [comment]
I believe this has been fixed in the latest bear:

```
2> bear:get_statistics_subset([1,2,3],[histogram]).
[{histogram,[{0,0}]}]
3> bear:get_statistics_subset([1,2,3,4],[histogram]).
[{histogram,[{0,0}]}]
4> bear:get_statistics_subset([1,2,3,4,5],[histogram]).
[{histogram,[{4,4},{7,1}]}]
```
