### ISSUE TITLE
A new tag for bear is needed

### ISSUE THREAD

**Issue by getong** [folsom-project/bear#12]
As erlang 21 version is released, many libraries is tested under 21, so the bear is need a new tag.
AS the new tag is updated, I will make a pr for folsom, and you might make a new tag for folsom, and finally you might push the new tag of the folsom to hex.pm.

**Comment by joewilliams** [comment]
I am happy to make the tags. @puzza007 do you have access to hex to push the tags up once they are created?

**Comment by puzza007** [comment]
Sure thing

**Comment by getong** [comment]
@joewilliams @puzza007  How is thing going?

**Comment by joewilliams** [comment]
I have tagged folsom and bear with 0.8.6.

**Comment by getong** [comment]
hex.pm tag not found, and folsom compile fail.

**Comment by puzza007** [comment]
Try now. I've pushed `0.8.6`. Note that I had to manually update `bear.app.src` locally because master is still on the previous version. Could cause problems. If so I guess we'll need to cut another version. @joewilliams you have ownership of bear too so you can publish.

**Comment by joewilliams** [comment]
Thanks @puzza007 I think I got all the tags and versions straightened out.

**Comment by jadeallenx** [comment]
The rebar.config on folsom asks for bear 0.8.7 which hasn't been pushed to hex yet.

**Comment by puzza007** [comment]
Published now 👍

**Comment by getong** [comment]
bear 0.8.7 found. folsom 0.8.7 is still not found.

**Comment by puzza007** [comment]
Oh right ok. Pushing that as well ```===> Published folsom 0.8.7```

**Comment by joewilliams** [comment]
Thanks everyone!
