### ISSUE TITLE
Please, push tags to this repository as well.

### ISSUE THREAD

**Issue by lemenkov** [folsom-project/bear#3]
Subj.

**Comment by lemenkov** [comment]
Ping, @joewilliams and sorry for the noise :)

**Comment by joewilliams** [comment]
@andy-dufour would you want to take this one?

**Comment by andy-dufour** [comment]
@joewilliams @lemenkov Pushed

**Comment by joewilliams** [comment]
Thanks!

**Comment by lemenkov** [comment]
@andy-dufour @joewilliams thanks!
