### ISSUE TITLE
Github link broken in hex.pm

### ISSUE THREAD

**Issue by ypaq** [folsom-project/bear#9]
[Bear package](https://hex.pm/packages/bear) in hex.pm links to `https://github.com/project-folsom/bear`. It should point to `https://github.com/folsom-project/bear`.

**Comment by puzza007** [comment]
Fixed in https://github.com/folsom-project/bear/commit/fb66ca27ecdf07517de8c71094f87fe4ddff09ad. I guess it'll go up in the next release to hex.pm.

**Comment by puzza007** [comment]
Fixed.
